version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=story_dot_challenge
      - POSTGRES_USER=lean
      - POSTGRES_PASSWORD=Lean123
    ports:
      - 5432:5432
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
  mysql:
    image:  mysql:5
    environment:
      - MYSEQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - "./mysql_data:/var/lib/mysql"

volumes: 
  postgres_data:
  

  
    
